package BigData.BigData_Topic2;

import java.io.IOException;
import java.util.List;

import org.neo4j.driver.v1.AuthTokens;
import org.neo4j.driver.v1.Driver;
import org.neo4j.driver.v1.GraphDatabase;
import org.neo4j.driver.v1.Session;
import org.neo4j.driver.v1.StatementResult;
import org.neo4j.driver.v1.Value;
import org.neo4j.driver.v1.Record;

/**
 * Main of project
 * 
 * In this main, we can run all query generated by the class Read_Graph_gmark
 */
public class App 
{
	public static void main( String[] args ) throws IOException
	{
		Read_Graph_gmark rGg = new Read_Graph_gmark();
		rGg.loadFile_buildQuery();

		List<String> queryList = rGg.getQuery();    	

		Driver driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "PasSW0rd"));
		
		try (Session session = driver.session()) {
			for (String query : queryList) {

				StatementResult rs = session.run(query);

				/*for (Record record : rs.list()) {
    	    		Value v = record.get(0);
    	    		System.out.println("Result : " + v.get("name").asString() + " " + record);
    	    	}*/
			}
			driver.close();
		}


	}
}
