package BigData.BigData_Topic2;

import java.io.*;
import java.util.ArrayList;
import java.util.List;


/* 
 * This method takes as input the graph generated by gmark and returns a list of strings in this case Cypher queries 
 * that will be useful after inserting them in the neo4j database
 * 
 */

public class Read_Graph_gmark {
	
	private File file = null;
	private List<String> result = null;
	
	public Read_Graph_gmark() {
		this.file = new File("input/play-graph0.txt");
		this.result = new ArrayList<String>();
	}
	
	public void loadFile_buildQuery() throws IOException {
		BufferedReader buffer = new BufferedReader(new FileReader(this.file));
		
		String st; 
		while ((st = buffer.readLine()) != null) {
			
			String[] parts = st.split(" ");
			String node1 = parts[0];
			String link = parts[1];
			String node2 = parts[2];
			
			String query = "MERGE (n1:Node {num:'"+node1+"'}) MERGE (n2:Node {num:'"+node2+"'}) CREATE (n1)-[:p"+link+"]-(n2)";
			
			result.add(query);
		}
		
	}
	
	public List<String> getQuery(){
		return this.result;
	}

}
